[package]
name = 'holo-credits'
version = '1.0.0'

[addresses]
HoloCredits = "_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
